### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by primepayment** [turmune/gitstart#1]
I think it looks better if the main title is a bit more orange.

The styling could be changed like this:

```css
h1 {
  color: #ecab3a;
}
```
